name: Test

on:
  workflow_dispatch:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.1.3'
    - name: Get dependencies
      run: flutter pub get
    - name: Analyze
      run: flutter analyze
    - name: Run tests
      run: flutter test
